version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
os: WMF 5
environment:
  AccessCredentialPassword:
    secure: +ssIq4M39yXq/VqooAUE56V8KUTDbxgQqB2SgG+edn2P16qNYtIzLWyEUlLhYqC7
clone_folder: c:\git\ScorchDev
init:
- ps: $env:PSModulePath = "$($env:PSModulePath);c:\git\ScorchDev\PowerShellModules"
nuget:
  disable_publish_on_pr: true
build: false
test_script:
- ps: >-
    & c:\git\SCOrchDev\Profile\profile.ps1

    $res = Invoke-Pester -Path "$($env:APPVEYOR_BUILD_FOLDER)\Tests" -OutputFormat NUnitXml -OutputFile c:\TestsResults.xml -PassThru

    (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", "c:\TestsResults.xml")

    if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}
deploy_script:
- ps: >-
    & c:\git\SCOrchDev\AppVeyor\deploy.ps1
